repos:
      # run ruff before black
      - repo: https://github.com/charliermarsh/ruff-pre-commit
        rev: 'v0.0.254'
        hooks:
          - id: ruff
            # attempt to automatically fix lint violations
            args: [--fix]
      - repo: https://github.com/ambv/black
        rev: 23.1.0
        hooks:
          - id: black
            language_version: python3.10
